site_name: VyHub Docs
site_url: https://docs.vyhub.net
nav:
  - Welcome: index.md
  - "Getting Started": 
    - getting_started/cloud.md
    - getting_started/selfhosting.md
  - "VyHub.net":
    - central/general.md
    - central/instance.md
    - central/custom_domain.md
    - central/account.md
    - central/affiliate.md
  - Guide:
    - guide/adverts.md
    - guide/authorization.md
    - guide/api.md
    - guide/ban.md
    - guide/customizability.md
    - guide/faq.md
    - guide/forum.md
    - guide/group.md
    - Import:
      - guide/import/general.md
      - guide/import/gextension.md
    - guide/html_pages.md
    - guide/legal.md
    - guide/navigation.md
    - guide/property.md
    - guide/requirement_set.md
    - guide/server.md
    - guide/serverbundle.md
    - Shop:
      - guide/shop/general.md
      - guide/shop/packet.md
      - guide/shop/payment_gateway.md
      - guide/shop/reward.md
      - guide/shop/tax.md
    - guide/team.md
    - guide/ticket.md
    - guide/user.md
    - guide/warning.md
  - Integrations:
    - game/asa.md
    - game/discord.md
    - game/fivem.md
    - game/gmod.md
    - game/minecraft.md
    - game/rust.md
    - game/teamspeak.md
    - game/7days.md
  - For Developers:
    - dev/css.md
    - dev/game_clients.md
    - dev/gmod.md
    - dev/selfhost_web.md
  - Changelog: changelog.md
  - Roadmap: roadmap.md
theme:
  name: material
  palette:
    scheme: slate
  logo: assets/logo.svg
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - content.code.copy
extra_css:
  - stylesheets/extra.css
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-CJW8RM10E1
plugins:
  - mike
  - search
  - redirects:
      redirect_maps:
        'quickstart.md': 'getting_started/cloud.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
